# Travis Environment Configuration

language: node_js
node_js:
  - "8.10"
notifications:
  email: false

# Travis Pipeline

before_script:
  - make deps

script:
  - make lint
  - make test

after_success:
  # only report serverless coverage for now
  - (cd ./serverless ; npm run coverage)
