# Travis Environment Configuration

language: node_js
node_js:
  - "8.10"
notifications:
  email: false

# Travis Pipeline

before_script:
  - make deps

script:
  - make lint   # static analysis
  - make build  # attempt to compile web app
  - make test   # run all tests

after_success:
  # only report serverless coverage for now
  - (cd ./serverless ; npm run coverage)
